version: "3.9"

services:

  nginx:
    labels: 
      - dev.orbstack.domains=${APP_NAME}.local
    image: nginx:latest
    restart: always
    env_file:
      - .env
    ports:
      - "${NGINX_ADDR_PORT:-80}:80"
    volumes:
      - ./src:/var/www/html      
      - ./log/nginx:/log/nginx
      - ./default.conf:/etc/nginx/conf.d/default.conf    
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm
      args:
        PHP_FPM_VERSION: ${PHP_FPM_VERSION:-8.2.7-fpm}
    restart: always
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
      - ./docker/profile.d:/etc/profile.d
      - ${PHP_INI:-./php-prod.ini}:/usr/local/etc/php/php.ini
      
  db:
    command: --max_allowed_packet=256M
    image: mariadb:10.5.9
    restart: always
    env_file:
      - .env
    volumes:
      - ${MYSQL_DATA_DIR:-./data}:/var/lib/mysql
    ports:
      - ${MYSQL_ADDR_PORT:-3306}:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always    
    env_file:
      - .env
    ports:
      - ${PMA_HTTP_ADDR_PORT:-21088}:80
    volumes:
      - ${PMA_USER_CONFIG_FILE:-/dev/null}:/etc/phpmyadmin/config.user.inc.php
  
